/**
 * Copyright © WarmHeart Intelligence Technology Group (Jiangsu) Co.,Ltd Company, Limited.
 * All Rights Reserved
 */
class StorageConst{
  static COOKIE_STAFF_NAME = "STAFF_NAME";
  static LOCAL_INSTITUTION_ID = "INSTITUTION_ID";
  static LOCAL_NAME = "LOCAL_NAME";
    static CURRENCY_NAME = "CURRENCY_NAME";
    static MENU_CODE_LIST = "MENU_CODE_LIST";

  static LOCAL_PAGE_LIST = {
    "ITEM_MAINTENANCE": "ITEM_MAINTENANCE",
    "PACKAGE_MAINTENANCE": "PACKAGE_MAINTENANCE",
    "PRICE_ADJUST_QUERY": "PRICE_ADJUST_QUERY",
    "MENU_DETAIL": "MENU_DETAIL",
    "MENU_DETAIL_PACKAGE": "MENU_DETAIL_PACKAGE",
    "LOG_QUERY": "LOG_QUERY",
    "STORE_CONF": "STORE_CONF",
    "STAFF_MAINTENANCE": "STAFF_MAINTENANCE",
    "ORDER_QUERY": "ORDER_QUERY",
    "BUSINESS_STATICES": "BUSINESS_STATICES",
    "SALE_STATICES": "SALE_STATICES",
	  "OPEN_BILL":"OPEN_BILL"
  };
}




export default StorageConst
